#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

PATH_TO_FILE=$1
SERVER_IP=$2
USERNAME=$3
SSH_P_KEY=$4

scp -i "$SSH_P_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$SERVER_IP:~/"
