#!/usr/bin/env bash
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

PATH_TO_FILE=$1
SERVER_IP=$2
USERNAME=$3
SSH_P_KEY=$4

scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PAHT_TO_FILE" "$USERNAME@$SERVER_IP:~/"
