#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request
# (requesting a page) using curl, it must return a page
# that contains the string Hello World

ssh -i "~/.ssh/id_rsa" "ubuntu@100.27.10.204" "sudo apt-get -y update && sudo apt-get -y install nginx && sudo bash -c 'echo \"Hello World!\" > /var/www/html/index.nginx-debian.html'"
