#!/usr/bin/env bash
# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Start Nginx server
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html

# Update Nginx configuration to add redirectin
sudo sed -i '/^}$/i \ \n\trewrite ^/redirect_me$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
