#!/usr/bin/env bash
# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create a new Nginx configuration file for the redirect
cat <<EOL | sudo tee /etc/nginx/sites-available/redirect
server {
	listen 80;
	server_name _;

	location /redirect_me {
		return 301 http:brehyma.tech;
	}
}
EOL

# Enable the new site by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

sudo service reload nginx
