#!/usr/bin/env bash
# Display lines containing the word "bash" and show the PID
# shellcheck disable=SC2009

# Use ps to list all processes (including those without a TTY)
# Filter lines containing "bash"
# Print the PID and the line
./1-list_your_processes | grep "bash"
