#!/usr/bin/env bash
# a Bash script that stops 4-to_infinity_and_beyond process.

# Find the PID of the process
PID=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Stop the process using kill
if [ -n "$PID" ]
then
	kill -15 "$PID"
fi
