#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with the below requirements.
sudo cp /etc/hosts /hosts.new
sed 's/127.0.0.1/127.0.0.2/' /hosts.new > /hosts.tmp
sudo cp -f /hosts.tmp /etc/hosts

if ! grep -Eq "^8\.8\.8\.8\s+facebook\.com$" /etc/hosts; then
	echo "8.8.8.8	facebook.com" | sudo tee -a /etc/hosts > /dev/null
fi
