#!/usr/bin/env bash
# This script use ssh to connect to a server using private key ~/.ssh/school with the user ubuntu.
SERVER_IP="100.27.10.204"
USER="ubuntu"
KEY="~/.ssh/school"

ssh -i $KEY $USER@$SERVER_IP
