#!/usr/bin/env bash
# This script that creates an RSA key pair.

# Variable
KEY_PATH="~/.ssh/school"
PASSPHRASE="betty"

# Generate the SSH key pair
ssh-keygen -t rsa -b 4096 -f $KEY_PATH -N "$PASSPHRASE"
