#!/usr/bin/env bash
# This script that creates an RSA key pair.

# Variable
KEY_PATH="$HOME/.ssh/school"
PASSPHRASE="betty"

mkdir -p "$HOME/.ssh"

# Generate the SSH key pair
ssh-keygen -t rsa -b 4096 -f $KEY_PATH -N "$PASSPHRASE"

chmod 600 $KEY_PATH
